name: Deploy to IBM Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to IBM Cloud
        uses: IBM-Cloud/ibmcloud-login-action@v1
        with:
          api_key: ${{ secrets.eD74yCehYsO3Fdo7RaPCq61J4esG20zJ_FUz_kkL-0Cf}}
          region: eu-gb

      - name: Build and push frontend Docker image
        id: build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.uk.icr.io }}/frontend:${{ github.sha }}

      - name: Build and push backend Docker image
        id: build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.uk.icr.io }}/backend:${{ github.sha }}

      - name: Deploy to IBM Cloud Code Engine
        uses: IBM/ibm-cloud-cli-cce-deploy@v1.0.0
        with:
          api_key: ${{ secrets.eD74yCehYsO3Fdo7RaPCq61J4esG20zJ_FUz_kkL-0Cf }}
          cluster: 2022-vetdb
          namespace: 2022-vetdb
          frontend_image: ${{ secrets.uk.icr.io }}/frontend:${{ github.sha }}
          backend_image: ${{ secrets.uk.icr.io }}/backend:${{ github.sha }}
